/** Handwritten / spoken aliases keyed by samagri product slug. */
export const SAMAGRI_ALIASES: Record<string, string[]> = {
  'samagri-turmeric': ['pasupu', 'haldi', 'turmeric', 'పసుపు', 'pasup'],
  'samagri-kumkum': ['kumkum', 'kunkum', 'kumkuma', 'కుంకుమ', 'కుంకుమం'],
  'samagri-ghee': ['ghee', 'neyyi', 'nei', 'neyi', 'నెయ్యి', 'నెయి'],
  'samagri-camphor': ['camphor', 'karpuram', 'karpooram', 'కర్పూరం', 'harati karpuram'],
  'samagri-incense': ['agarbatti', 'agarbathi', 'incense', 'అగరబత్తీ', 'అగరబత్తీలు'],
  'samagri-coconuts': ['coconut', 'kobbari', 'kobbarikaya', 'కొబ్బరికాయ', 'కొబ్బరికాయలు'],
  'samagri-rice': ['rice', 'biyyam', 'biyam', 'బియ్యం'],
  'samagri-jaggery': ['jaggery', 'bellam', 'belam', 'బెల్లం'],
  'samagri-betel-leaves': ['betel leaves', 'tamalapaku', 'tamalapakulu', 'తామలపాక', 'తామలపాకులు'],
  'samagri-flowers': ['flowers', 'puvulu', 'puvvulu', 'poolu', 'పూలు', 'పువ్వులు', 'vidi poolu'],
  'samagri-mango-leaves': ['mango leaves', 'mamidakulu', 'maamidakulu', 'మామిడాకులు'],
  'samagri-gandham': ['gandham', 'sandal', 'sandal paste', 'chandana', 'గంధం'],
  'samagri-akshatalu': ['akshatalu', 'akshintalu', 'akshata', 'అక్షతలు', 'అక్షింతలు'],
  'samagri-betel-nuts': ['betel nuts', 'vakkalu', 'vakalu', 'వక్కలు'],
  'samagri-cotton-wicks': ['wicks', 'vattulu', 'cotton wicks', 'వత్తులు'],
  'samagri-diya-wicks': ['diya wicks', 'divvi vattulu', 'దివ్వి వత్తులు'],
  'samagri-oil': ['oil', 'nune', 'groundnut oil', 'నూనె'],
  'samagri-durva': ['durva', 'garika', 'isthari', 'garika pasupu', 'గరిక', 'ఇస్తరి'],
  'samagri-homa-powder': ['homa powder', 'homam podi', 'హోమం పొడి'],
  'samagri-navadhanyalu': ['navadhanyalu', 'navadhanyam', 'నవధాన్యాలు'],
  'samagri-samithalu': ['samithalu', 'samidalu', 'homa sticks', 'సమితలు'],
  'samagri-fruits': ['fruits', 'pandlu', 'పండ్లు'],
  'samagri-kalasham': ['kalasham', 'kalasam', 'kalash', 'కలశం'],
  'samagri-dhoti': ['dhoti', 'dhothi', 'ధోతి'],
  'samagri-bananas': ['bananas', 'aratipandlu', 'అరటిపండ్లు'],
  'samagri-cashews': ['cashews', 'jeedipappu', 'జీడిపప్పు'],
  'samagri-toranam': ['toranam', 'thoranam', 'తోరణం'],
  'samagri-blouse-pieces': ['blouse piece', 'blouse pieces', 'jacket piece', 'జాకెట్'],
  'samagri-purnahuti': ['purnahuti', 'purnahutti', 'పూర్ణాహుతి'],
  'samagri-isthari-leaves': ['isthari', 'durva leaves', 'ఇస్తరి ఆకులు'],
  'samagri-copper-pot': ['ragi chembu', 'chembu', 'copper pot', 'రాగి చెంబు'],
  'samagri-small-diyas': ['matti depalu', 'matti deepalu', 'clay lamps', 'మట్టి దీపాలు'],
};

export const ENGLISH_CANONICAL_ALIASES: Record<string, string> = {
  Turmeric: 'Turmeric (Pasupu)',
  'Sandal paste': 'Sandal paste (Gandham)',
  Akshintalu: 'Akshatalu (turmeric rice)',
  'Betel nuts': 'Betel nuts (Vakkalu)',
  Flowers: 'Loose flowers',
  'Dried coconut': 'Dried coconuts',
  Wicks: 'Cotton wicks',
  Deepam: 'Akhanda deepam',
  'Mango leaves for toranam': 'Mango leaves',
  'Blouse piece': 'Blouse pieces',
  'Blouse piece (Jacket piece)': 'Blouse pieces',
  'Arati camphor': 'Camphor',
  'Isthari leaves (Durva)': 'Durva / isthari leaves',
};
