export const TITHIS = [
  'Pratipada',
  'Dwitiya',
  'Tritiya',
  'Chaturthi',
  'Panchami',
  'Shashthi',
  'Saptami',
  'Ashtami',
  'Navami',
  'Dashami',
  'Ekadashi',
  'Dwadashi',
  'Trayodashi',
  'Chaturdashi',
  'Purnima/Amavasya',
] as const;

export const NAKSHATRAS = [
  'Ashwini',
  'Bharani',
  'Krittika',
  'Rohini',
  'Mrigashira',
  'Ardra',
  'Punarvasu',
  'Pushya',
  'Ashlesha',
  'Magha',
  'Purva Phalguni',
  'Uttara Phalguni',
  'Hasta',
  'Chitra',
  'Swati',
  'Vishakha',
  'Anuradha',
  'Jyeshtha',
  'Mula',
  'Purva Ashadha',
  'Uttara Ashadha',
  'Shravana',
  'Dhanishta',
  'Shatabhisha',
  'Purva Bhadrapada',
  'Uttara Bhadrapada',
  'Revati',
] as const;

export const YOGAS = [
  'Vishkambha',
  'Priti',
  'Ayushman',
  'Saubhagya',
  'Shobhana',
  'Atiganda',
  'Sukarma',
  'Dhriti',
  'Shula',
  'Ganda',
  'Vriddhi',
  'Dhruva',
  'Vyaghata',
  'Harshana',
  'Vajra',
  'Siddhi',
  'Vyatipata',
  'Variyan',
  'Parigha',
  'Shiva',
  'Siddha',
  'Sadhya',
  'Shubha',
  'Shukla',
  'Brahma',
  'Indra',
  'Vaidhriti',
] as const;

export const KARANAS = [
  'Bava',
  'Balava',
  'Kaulava',
  'Taitila',
  'Gara',
  'Vanija',
  'Vishti',
  'Shakuni',
  'Chatushpada',
  'Nagava',
  'Kimstughna',
] as const;

/** 60-year Telugu/Kannada cycle. 1987 CE (after Ugadi) = Prabhava. */
export const SAMVATSARA_NAMES = [
  'Prabhava',
  'Vibhava',
  'Shukla',
  'Pramoduta',
  'Prajotpatti',
  'Angirasa',
  'Shrimukha',
  'Bhava',
  'Yuva',
  'Dhata',
  'Ishvara',
  'Bahudhanya',
  'Pramadi',
  'Vikrama',
  'Vrisha',
  'Chitrabhanu',
  'Svabhanu',
  'Tarana',
  'Parthiva',
  'Vyaya',
  'Sarvajit',
  'Sarvadhari',
  'Virodhi',
  'Vikriti',
  'Khara',
  'Nandana',
  'Vijaya',
  'Jaya',
  'Manmatha',
  'Durmukhi',
  'Hevilambi',
  'Vilambi',
  'Vikari',
  'Sharvari',
  'Plava',
  'Shubhakrit',
  'Shobhakrit',
  'Krodhi',
  'Vishvavasu',
  'Parabhava',
  'Plavanga',
  'Kilaka',
  'Saumya',
  'Sadharana',
  'Virodhikrit',
  'Paridhavi',
  'Pramadicha',
  'Ananda',
  'Rakshasa',
  'Nala',
  'Pingala',
  'Kalayukti',
  'Siddharthi',
  'Raudra',
  'Durmati',
  'Dundubhi',
  'Rudhirodgari',
  'Raktakshi',
  'Krodhana',
  'Akshaya',
] as const;

export const RASI_NAMES = [
  'Mesha',
  'Vrishabha',
  'Mithuna',
  'Karka',
  'Simha',
  'Kanya',
  'Tula',
  'Vrishchika',
  'Dhanu',
  'Makara',
  'Kumbha',
  'Meena',
] as const;

/** Lunar/solar month names in Chaitradi order (Mesha = Chaitra). */
export const MASA_NAMES = [
  'Chaitra',
  'Vaisakha',
  'Jyeshtha',
  'Ashadha',
  'Shravana',
  'Bhadrapada',
  'Ashwayuja',
  'Kartika',
  'Margashira',
  'Pushya',
  'Magha',
  'Phalguna',
] as const;

export const RITHU_NAMES = [
  'Vasanta',
  'Grishma',
  'Varsha',
  'Sharad',
  'Hemanta',
  'Shishira',
] as const;

export const RASI_LABELS: Record<string, string> = {
  MESHA: 'Mesha (Aries)',
  VRISHABHA: 'Vrishabha (Taurus)',
  MITHUNA: 'Mithuna (Gemini)',
  KARKA: 'Karka (Cancer)',
  SIMHA: 'Simha (Leo)',
  KANYA: 'Kanya (Virgo)',
  TULA: 'Tula (Libra)',
  VRISHCHIKA: 'Vrishchika (Scorpio)',
  DHANU: 'Dhanu (Sagittarius)',
  MAKARA: 'Makara (Capricorn)',
  KUMBHA: 'Kumbha (Aquarius)',
  MEENA: 'Meena (Pisces)',
};

export const CITY_PRESETS = [
  {
    name: 'Bengaluru',
    latitude: 12.9716,
    longitude: 77.5946,
    timezone: 'Asia/Kolkata',
  },
  {
    name: 'Hyderabad',
    latitude: 17.385,
    longitude: 78.4867,
    timezone: 'Asia/Kolkata',
  },
  {
    name: 'Delhi',
    latitude: 28.6139,
    longitude: 77.209,
    timezone: 'Asia/Kolkata',
  },
  {
    name: 'Mumbai',
    latitude: 19.076,
    longitude: 72.8777,
    timezone: 'Asia/Kolkata',
  },
  {
    name: 'New York',
    latitude: 40.7128,
    longitude: -74.006,
    timezone: 'America/New_York',
  },
  {
    name: 'Toronto',
    latitude: 43.6532,
    longitude: -79.3832,
    timezone: 'America/Toronto',
  },
] as const;
