import type { Locale } from "./types";

const dict = {
  kicker: { en: "Your seva", te: "మీ సేవ" },
  title: { en: "My profile", te: "నా ప్రొఫైల్" },
  namaste: { en: "Namaste", te: "నమస్తే" },
  loading: { en: "Loading your account…", te: "ఖాతా లోడ్ అవుతోంది…" },
  guestTitle: { en: "Sign in to manage your account", te: "మీ ఖాతాను నిర్వహించడానికి సైన్ ఇన్ చేయండి" },
  orders: { en: "My orders", te: "నా ఆర్డర్లు" },
  ordersHint: { en: "Kits, samagri, and delivery status", te: "కిట్‌లు, సామగ్రి, డెలివరీ స్థితి" },
  cart: { en: "Cart", te: "కార్ట్" },
  cartHint: { en: "Items waiting for checkout", te: "చెక్అవుట్ కోసం వేచి ఉన్నవి" },
  addresses: { en: "Saved addresses", te: "సేవ్ చేసిన చిరునామాలు" },
  addressesHint: { en: "Home, office, and delivery pins", te: "ఇల్లు, ఆఫీసు, డెలివరీ" },
  personal: { en: "Personal details", te: "వ్యక్తిగత వివరాలు" },
  personalHint: { en: "Name, email, and language", te: "పేరు, ఇమెయిల్, భాష" },
  security: { en: "Password & security", te: "పాస్‌వర్డ్ మరియు భద్రత" },
  securityHint: { en: "Change or set your password", te: "పాస్‌వర్డ్ మార్చండి లేదా సెట్ చేయండి" },
  bookings: { en: "Priest bookings", te: "పూజారి బుకింగ్‌లు" },
  bookingsHint: { en: "Home visits and online seva", te: "ఇంటి సేవ మరియు ఆన్‌లైన్" },
  packages: { en: "Pooja packages", te: "పూజా ప్యాకేజీలు" },
  birth: { en: "Birth & panchang profile", te: "జననం మరియు పంచాంగం" },
  birthHint: { en: "Rasi, nakshatra, gotram, city", te: "రాశి, నక్షత్రం, గోత్రం, నగరం" },
  panchangToday: { en: "Today's panchang", te: "నేటి పంచాంగం" },
  notifications: { en: "Notifications", te: "నోటిఫికేషన్లు" },
  notificationsHint: { en: "Orders, bookings, and reminders", te: "ఆర్డర్లు, బుకింగ్‌లు, జ్ఞాపికలు" },
  priests: { en: "Book a priest", te: "పూజారిని బుక్ చేయండి" },
  joinPujari: { en: "Join as a pujari", te: "పూజారిగా చేరండి" },
  pujariDesk: { en: "Pujari desk", te: "పూజారి డెస్క్" },
  support: { en: "Help & support", te: "సహాయం" },
  supportHint: { en: "Email us or read policies", te: "ఇమెయిల్ లేదా విధానాలు" },
  privacy: { en: "Privacy policy", te: "గోప్యతా విధానం" },
  about: { en: "About Pavitra Seva", te: "పవిత్ర సేవ గురించి" },
  language: { en: "Language", te: "భాష" },
  logout: { en: "Log out", te: "లాగ్ అవుట్" },
  back: { en: "Back to profile", te: "ప్రొఫైల్‌కు తిరిగి" },
  save: { en: "Save", te: "సేవ్" },
  saving: { en: "Saving…", te: "సేవ్ అవుతోంది…" },
  saved: { en: "Saved", te: "సేవ్ అయింది" },
  groupAccount: { en: "Account", te: "ఖాతా" },
  groupOrders: { en: "Orders & bookings", te: "ఆర్డర్లు మరియు బుకింగ్‌లు" },
  groupSpiritual: { en: "Spiritual profile", te: "ఆధ్యాత్మిక ప్రొఫైల్" },
  groupHelp: { en: "Help", te: "సహాయం" },
  phoneLocked: { en: "Phone number", te: "ఫోన్ నంబర్" },
  phoneHint: { en: "Used for delivery and priest visits. Contact support to change it.", te: "డెలివరీ మరియు పూజారి సందర్శనలకు. మార్చాలంటే సపోర్ట్‌ను సంప్రదించండి." },
  fullName: { en: "Full name", te: "పూర్తి పేరు" },
  email: { en: "Email", te: "ఇమెయిల్" },
  english: { en: "English", te: "ఇంగ్లీష్" },
  telugu: { en: "Telugu", te: "తెలుగు" },
  addAddress: { en: "Add address", te: "చిరునామా జోడించు" },
  noAddresses: { en: "No saved addresses yet. Add one for faster checkout.", te: "చిరునామాలు లేవు. చెక్అవుట్ కోసం ఒకటి జోడించండి." },
  default: { en: "Default", te: "డిఫాల్ట్" },
  makeDefault: { en: "Make default", te: "డిఫాల్ట్ చేయి" },
  delete: { en: "Remove", te: "తొలగించు" },
  label: { en: "Label", te: "పేరు" },
  line1: { en: "Address line", te: "చిరునామా" },
  city: { en: "City", te: "నగరం" },
  state: { en: "State", te: "రాష్ట్రం" },
  pin: { en: "PIN / ZIP", te: "పిన్" },
  noBookings: { en: "No priest bookings yet.", te: "పూజారి బుకింగ్‌లు లేవు." },
  noPackages: { en: "No package bookings yet.", te: "ప్యాకేజీ బుకింగ్‌లు లేవు." },
  cancelBooking: { en: "Cancel", te: "రద్దు" },
  noNotifications: { en: "You are all caught up.", te: "కొత్త నోటిఫికేషన్లు లేవు." },
  markAllRead: { en: "Mark all read", te: "అన్నీ చదివినట్లు" },
  currentPassword: { en: "Current password", te: "ప్రస్తుత పాస్‌వర్డ్" },
  newPassword: { en: "New password", te: "కొత్త పాస్‌వర్డ్" },
  confirmPassword: { en: "Confirm new password", te: "కొత్త పాస్‌వర్డ్ నిర్ధారించండి" },
  setPassword: { en: "Set a password", te: "పాస్‌వర్డ్ సెట్ చేయండి" },
  changePassword: { en: "Update password", te: "పాస్‌వర్డ్ నవీకరించు" },
  passwordHint: {
    en: "At least 8 characters. Google or Apple sign-in still works after you set a password.",
    te: "కనీసం 8 అక్షరాలు. పాస్‌వర్డ్ సెట్ చేసినా Google లేదా Apple సైన్-ఇన్ పని చేస్తుంది.",
  },
  mismatch: { en: "New passwords do not match.", te: "కొత్త పాస్‌వర్డ్‌లు సరిపోలడం లేదు." },
  dob: { en: "Date of birth", te: "పుట్టిన తేది" },
  birthTime: { en: "Birth time", te: "జనన సమయం" },
  birthPlace: { en: "Birth place", te: "జన్మ స్థలం" },
  rasi: { en: "Rasi", te: "రాశి" },
  nakshatra: { en: "Nakshatra", te: "నక్షత్రం" },
  gotram: { en: "Gotram", te: "గోత్రం" },
  panchangCity: { en: "Panchang city", te: "పంచాంగ నగరం" },
  supportEmail: { en: "Email support", te: "ఇమెయిల్ సపోర్ట్" },
  supportBody: {
    en: "We typically reply within one business day. Include your order number if you have one.",
    te: "సాధారణంగా ఒక పని రోజులో సమాధానం ఇస్తాము. ఆర్డర్ నంబర్ ఉంటే పంపండి.",
  },
  memberSince: { en: "Member since", te: "సభ్యుడు అయినప్పటి నుంచి" },
} as const;

export type AccountCopyKey = keyof typeof dict;

export function ac(locale: Locale, key: AccountCopyKey) {
  return dict[key][locale];
}
