export type GaneshSamagriLine = {
  slug: string;
  nameEn: string;
  nameTe: string;
  packEn?: string;
  packTe?: string;
  quantity?: number;
  optional?: boolean;
};

export const ganeshMiniHomeItems: GaneshSamagriLine[] = [
  { slug: "samagri-dhoop-cups", nameEn: "Dhoop cups", nameTe: "ధూపం కప్పులు", quantity: 2 },
  { slug: "samagri-matchbox", nameEn: "Matchbox", nameTe: "అగ్గిపెట్టె" },
  { slug: "samagri-kankana-thread", nameEn: "Kankana thread", nameTe: "కంకణాల దారం" },
  { slug: "samagri-kumkum", nameEn: "Kumkum", nameTe: "కుంకుమ", packEn: "10g", packTe: "10 గ్రా" },
  { slug: "samagri-yajnopavita", nameEn: "Yajnopavita", nameTe: "యజ్ఞోపవీతం" },
  { slug: "samagri-sutli", nameEn: "Sutli thread", nameTe: "సుత్లీ దారం" },
  { slug: "samagri-turmeric", nameEn: "Turmeric (Pasupu)", nameTe: "పసుపు", packEn: "10g", packTe: "10 గ్రా" },
  { slug: "samagri-gandham", nameEn: "Sandal paste (Gandham)", nameTe: "గంధం", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-akshatalu", nameEn: "Akshatalu (turmeric rice)", nameTe: "అక్షింతలు", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-gulal", nameEn: "Gulal", nameTe: "గులాల్", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-bukka", nameEn: "Bukka", nameTe: "బుక్కా" },
  { slug: "samagri-camphor", nameEn: "Camphor", nameTe: "కర్పూరం", packEn: "1 pack", packTe: "1 ప్యాక్" },
  { slug: "samagri-incense", nameEn: "Incense sticks", nameTe: "అగరబత్తులు", packEn: "1 pack", packTe: "1 ప్యాక్" },
  { slug: "samagri-leaf-cups", nameEn: "Prasadam leaf cups", nameTe: "ప్రసాదం దోనెలు", quantity: 10 },
  { slug: "samagri-jaggery", nameEn: "Jaggery", nameTe: "బెల్లం", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-honey", nameEn: "Honey", nameTe: "తేనె", packEn: "25 ml", packTe: "25 మి.లీ." },
  { slug: "samagri-rava", nameEn: "Rava", nameTe: "రవ్వ", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-sugar-crystals", nameEn: "Sugar crystals", nameTe: "పంచదార బిళ్లలు", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-coconuts", nameEn: "Coconuts", nameTe: "కొబ్బరికాయలు" },
  { slug: "samagri-rose-water", nameEn: "Rose water", nameTe: "పన్నీరు", packEn: "25 ml", packTe: "25 మి.లీ." },
  { slug: "samagri-ghee", nameEn: "Ghee", nameTe: "నెయ్యి", packEn: "25 ml", packTe: "25 మి.లీ." },
  { slug: "samagri-oil", nameEn: "Oil", nameTe: "నూనె", packEn: "50 ml", packTe: "50 మి.లీ." },
  { slug: "samagri-betel-leaves", nameEn: "Betel leaves", nameTe: "తమలపాకులు", quantity: 5 },
  { slug: "samagri-betel-nuts", nameEn: "Betel nuts (Vakkalu)", nameTe: "వక్కలు" },
  { slug: "samagri-turmeric-roots", nameEn: "Turmeric roots", nameTe: "పసుపు కొమ్ములు" },
  { slug: "samagri-cotton-wicks", nameEn: "Cotton wicks", nameTe: "వత్తులు", packEn: "1 pack", packTe: "1 ప్యాక్" },
  { slug: "samagri-eco-ganesh-idol", nameEn: "Eco-friendly clay Ganesh idol", nameTe: "పర్యావరణ అనుకూల మట్టి గణేష్ విగ్రహం" },
  { slug: "samagri-red-cloth", nameEn: "Red cloth", nameTe: "ఎర్రని బట్ట" },
  { slug: "samagri-paper-umbrella", nameEn: "Paper umbrella", nameTe: "కాగితపు గొడుగు" },
  { slug: "samagri-pooja-book", nameEn: "Pooja vidhanam book", nameTe: "పూజా విధానం పుస్తకం" },
];

export const ganeshMiniOfficeItems: GaneshSamagriLine[] = [
  { slug: "samagri-dhoop-cups", nameEn: "Dhoop cups", nameTe: "ధూపం కప్పులు", quantity: 2 },
  { slug: "samagri-matchbox", nameEn: "Matchbox", nameTe: "అగ్గిపెట్టె", quantity: 2 },
  { slug: "samagri-kankana-thread", nameEn: "Kankana thread", nameTe: "కంకణాల దారం" },
  { slug: "samagri-kumkum", nameEn: "Kumkum", nameTe: "కుంకుమ", packEn: "50g", packTe: "50 గ్రా" },
  { slug: "samagri-yajnopavita", nameEn: "Yajnopavita", nameTe: "యజ్ఞోపవీతం" },
  { slug: "samagri-sutli", nameEn: "Sutli thread", nameTe: "సుత్లీ దారం" },
  { slug: "samagri-turmeric", nameEn: "Turmeric (Pasupu)", nameTe: "పసుపు", packEn: "50g", packTe: "50 గ్రా" },
  { slug: "samagri-gandham", nameEn: "Sandal paste (Gandham)", nameTe: "గంధం", packEn: "50g", packTe: "50 గ్రా" },
  { slug: "samagri-akshatalu", nameEn: "Akshatalu (turmeric rice)", nameTe: "అక్షింతలు", packEn: "2000g", packTe: "2000 గ్రా" },
  { slug: "samagri-gulal", nameEn: "Gulal", nameTe: "గులాల్", quantity: 12 },
  { slug: "samagri-bukka", nameEn: "Bukka", nameTe: "బుక్కా", quantity: 12 },
  { slug: "samagri-camphor", nameEn: "Camphor", nameTe: "కర్పూరం", packEn: "1 pack", packTe: "1 ప్యాక్" },
  { slug: "samagri-incense", nameEn: "Incense sticks", nameTe: "అగరబత్తులు", packEn: "1 pack", packTe: "1 ప్యాక్" },
  { slug: "samagri-leaf-cups", nameEn: "Prasadam leaf cups", nameTe: "ప్రసాదం దోనెలు", quantity: 25 },
  { slug: "samagri-jaggery", nameEn: "Jaggery", nameTe: "బెల్లం", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-honey", nameEn: "Honey", nameTe: "తేనె", packEn: "50 ml", packTe: "50 మి.లీ." },
  { slug: "samagri-rava", nameEn: "Rava", nameTe: "రవ్వ", packEn: "100g", packTe: "100 గ్రా" },
  { slug: "samagri-sugar-crystals", nameEn: "Sugar crystals", nameTe: "పంచదార బిళ్లలు", packEn: "100g", packTe: "100 గ్రా" },
  { slug: "samagri-coconuts", nameEn: "Coconuts", nameTe: "కొబ్బరికాయలు" },
  { slug: "samagri-rose-water", nameEn: "Rose water", nameTe: "పన్నీరు", packEn: "50 ml", packTe: "50 మి.లీ." },
  { slug: "samagri-ghee", nameEn: "Ghee", nameTe: "నెయ్యి", packEn: "100 ml", packTe: "100 మి.లీ." },
  { slug: "samagri-oil", nameEn: "Oil", nameTe: "నూనె", packEn: "250 ml", packTe: "250 మి.లీ." },
  { slug: "samagri-betel-leaves", nameEn: "Betel leaves", nameTe: "తమలపాకులు", quantity: 10 },
  { slug: "samagri-betel-nuts", nameEn: "Betel nuts (Vakkalu)", nameTe: "వక్కలు", quantity: 5 },
  { slug: "samagri-turmeric-roots", nameEn: "Turmeric roots", nameTe: "పసుపు కొమ్ములు", quantity: 5 },
  { slug: "samagri-cotton-wicks", nameEn: "Cotton wicks", nameTe: "వత్తులు", packEn: "1 pack", packTe: "1 ప్యాక్" },
  { slug: "samagri-eco-ganesh-idol", nameEn: "Eco-friendly clay Ganesh idol", nameTe: "పర్యావరణ అనుకూల మట్టి గణేష్ విగ్రహం" },
  { slug: "samagri-red-cloth", nameEn: "Red cloth", nameTe: "ఎర్రని బట్ట" },
  { slug: "samagri-paper-umbrella", nameEn: "Paper umbrella", nameTe: "కాగితపు గొడుగు" },
  { slug: "samagri-pooja-book", nameEn: "Pooja vidhanam book", nameTe: "పూజా విధానం పుస్తకం" },
];

export const ganeshMiniMandapamItems: GaneshSamagriLine[] = [
  { slug: "samagri-dhoop-cups", nameEn: "Dhoop cups", nameTe: "ధూపం కప్పులు", quantity: 5 },
  { slug: "samagri-matchbox", nameEn: "Matchbox", nameTe: "అగ్గిపెట్టె", quantity: 5 },
  { slug: "samagri-kankana-thread", nameEn: "Kankana thread", nameTe: "కంకణాల దారం", quantity: 10 },
  { slug: "samagri-kumkum", nameEn: "Kumkum", nameTe: "కుంకుమ", packEn: "250g", packTe: "250 గ్రా" },
  { slug: "samagri-yajnopavita", nameEn: "Yajnopavita", nameTe: "యజ్ఞోపవీతం", quantity: 10 },
  { slug: "samagri-sutli", nameEn: "Sutli thread", nameTe: "సుత్లీ దారం", quantity: 10 },
  { slug: "samagri-turmeric", nameEn: "Turmeric (Pasupu)", nameTe: "పసుపు", packEn: "250g", packTe: "250 గ్రా" },
  { slug: "samagri-gandham", nameEn: "Sandal paste (Gandham)", nameTe: "గంధం", packEn: "250g", packTe: "250 గ్రా" },
  { slug: "samagri-akshatalu", nameEn: "Akshatalu (turmeric rice)", nameTe: "అక్షింతలు", packEn: "5000g", packTe: "5000 గ్రా" },
  { slug: "samagri-gulal", nameEn: "Gulal", nameTe: "గులాల్", quantity: 50 },
  { slug: "samagri-bukka", nameEn: "Bukka", nameTe: "బుక్కా", quantity: 50 },
  { slug: "samagri-camphor", nameEn: "Camphor", nameTe: "కర్పూరం", packEn: "1 pack", packTe: "1 ప్యాక్" },
  { slug: "samagri-incense", nameEn: "Incense sticks", nameTe: "అగరబత్తులు", packEn: "5 packs", packTe: "5 ప్యాక్‌లు", quantity: 5 },
  { slug: "samagri-leaf-cups", nameEn: "Prasadam leaf cups", nameTe: "ప్రసాదం దోనెలు", quantity: 100 },
  { slug: "samagri-jaggery", nameEn: "Jaggery", nameTe: "బెల్లం", packEn: "1000g", packTe: "1000 గ్రా" },
  { slug: "samagri-honey", nameEn: "Honey", nameTe: "తేనె", packEn: "500 ml", packTe: "500 మి.లీ." },
  { slug: "samagri-rava", nameEn: "Rava", nameTe: "రవ్వ", packEn: "1000g", packTe: "1000 గ్రా" },
  { slug: "samagri-sugar-crystals", nameEn: "Sugar crystals", nameTe: "పంచదార బిళ్లలు", packEn: "500g", packTe: "500 గ్రా" },
  { slug: "samagri-coconuts", nameEn: "Coconuts", nameTe: "కొబ్బరికాయలు", quantity: 18 },
  { slug: "samagri-rose-water", nameEn: "Rose water", nameTe: "పన్నీరు", packEn: "500 ml", packTe: "500 మి.లీ." },
  { slug: "samagri-ghee", nameEn: "Ghee", nameTe: "నెయ్యి", packEn: "500 ml", packTe: "500 మి.లీ." },
  { slug: "samagri-oil", nameEn: "Oil", nameTe: "నూనె", packEn: "2000 ml", packTe: "2000 మి.లీ." },
  { slug: "samagri-betel-leaves", nameEn: "Betel leaves", nameTe: "తమలపాకులు", quantity: 100 },
  { slug: "samagri-betel-nuts", nameEn: "Betel nuts (Vakkalu)", nameTe: "వక్కలు", quantity: 50 },
  { slug: "samagri-turmeric-roots", nameEn: "Turmeric roots", nameTe: "పసుపు కొమ్ములు", quantity: 25 },
  { slug: "samagri-cotton-wicks", nameEn: "Cotton wicks", nameTe: "వత్తులు", packEn: "10 packs", packTe: "10 ప్యాక్‌లు", quantity: 10 },
  { slug: "samagri-eco-ganesh-idol", nameEn: "Eco-friendly clay Ganesh idol", nameTe: "పర్యావరణ అనుకూల మట్టి గణేష్ విగ్రహం" },
  { slug: "samagri-red-cloth", nameEn: "Red cloth", nameTe: "ఎర్రని బట్ట", packEn: "3 m", packTe: "3 మీ" },
  { slug: "samagri-paper-umbrella", nameEn: "Paper umbrella", nameTe: "కాగితపు గొడుగు" },
  { slug: "samagri-pooja-book", nameEn: "Pooja vidhanam book", nameTe: "పూజా విధానం పుస్తకం" },
];

export const ganeshMegaHomeItems: GaneshSamagriLine[] = [
  { slug: "samagri-eco-ganesh-idol", nameEn: "Eco-friendly clay Ganesh idol", nameTe: "పర్యావరణ అనుకూల మట్టి గణేష్ విగ్రహం" },
  { slug: "samagri-markatam-ganesh", nameEn: "Markatam Ganesh", nameTe: "మార్కటం గణేష్" },
  { slug: "samagri-turmeric", nameEn: "Turmeric (Pasupu)", nameTe: "పసుపు", packEn: "10g", packTe: "10 గ్రా" },
  { slug: "samagri-kumkum", nameEn: "Kumkum", nameTe: "కుంకుమ", packEn: "10g", packTe: "10 గ్రా" },
  { slug: "samagri-sindoor", nameEn: "Sindoor", nameTe: "సింధూరం", packEn: "5g", packTe: "5 గ్రా" },
  { slug: "samagri-bukka", nameEn: "Bukka", nameTe: "బుక్కా" },
  { slug: "samagri-gulal", nameEn: "Gulal", nameTe: "గులాల్", packEn: "5g", packTe: "5 గ్రా" },
  { slug: "samagri-rice-flour", nameEn: "Rice flour", nameTe: "బియ్యం పిండి", packEn: "250g", packTe: "250 గ్రా" },
  { slug: "samagri-rice", nameEn: "Rice", nameTe: "బియ్యం", packEn: "1000g", packTe: "1000 గ్రా" },
  { slug: "samagri-astagandham", nameEn: "Astagandham", nameTe: "అష్టగంధం", packEn: "50g", packTe: "50 గ్రా" },
  { slug: "samagri-javadhu", nameEn: "Javadhu", nameTe: "జావాదు", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-attar", nameEn: "Attar", nameTe: "అత్తరు", packEn: "1 bottle", packTe: "1 సీసా" },
  { slug: "samagri-dhoop-cups", nameEn: "Dhoop cups", nameTe: "ధూపం కప్పులు", quantity: 20 },
  { slug: "samagri-incense", nameEn: "Incense sticks", nameTe: "అగరబత్తులు", packEn: "2 packs", packTe: "2 ప్యాక్‌లు", quantity: 2 },
  { slug: "samagri-camphor", nameEn: "Camphor", nameTe: "కర్పూరం", packEn: "100g", packTe: "100 గ్రా" },
  { slug: "samagri-pacha-karpuram", nameEn: "Pacha karpuram", nameTe: "పచ్చ కర్పూరం", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-cotton-wicks", nameEn: "Cotton wicks", nameTe: "వత్తులు", packEn: "2 packs", packTe: "2 ప్యాక్‌లు", quantity: 2 },
  { slug: "samagri-puvvu-wicks", nameEn: "Puvvu vathulu", nameTe: "పువ్వు వత్తులు", packEn: "1 pack", packTe: "1 ప్యాక్" },
  { slug: "samagri-jileda-wicks", nameEn: "Jileda vathulu", nameTe: "జిలేడు వత్తులు", packEn: "1 pack", packTe: "1 ప్యాక్" },
  { slug: "samagri-puja-vastras", nameEn: "Puja vastras", nameTe: "పూజా వస్త్రాలు" },
  { slug: "samagri-akhanda-deepam", nameEn: "Akhanda deepam", nameTe: "అఖండ దీపం" },
  { slug: "samagri-dates", nameEn: "Dates", nameTe: "ఖర్జూరాలు", packEn: "100g", packTe: "100 గ్రా" },
  { slug: "samagri-turmeric-roots", nameEn: "Turmeric roots", nameTe: "పసుపు కొమ్ములు", quantity: 11 },
  { slug: "samagri-betel-nuts", nameEn: "Betel nuts (Vakkalu)", nameTe: "వక్కలు", quantity: 11 },
  { slug: "samagri-poha", nameEn: "Poha (Atukulu)", nameTe: "అటుకులు", packEn: "250g", packTe: "250 గ్రా" },
  { slug: "samagri-jaggery", nameEn: "Jaggery", nameTe: "బెల్లం", packEn: "250g", packTe: "250 గ్రా" },
  { slug: "samagri-cloves", nameEn: "Cloves", nameTe: "లవంగాలు", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-cardamom", nameEn: "Cardamom", nameTe: "యాలకులు", packEn: "25g", packTe: "25 గ్రా" },
  { slug: "samagri-white-thread", nameEn: "White thread", nameTe: "తెల్ల దారం", packEn: "1 roll", packTe: "1 రోల్" },
  { slug: "samagri-sutli", nameEn: "Sutli thread", nameTe: "సుత్లీ దారం", packEn: "1 roll", packTe: "1 రోల్" },
  { slug: "samagri-moli-thread", nameEn: "Moli thread", nameTe: "మౌలి దారం", quantity: 10 },
  { slug: "samagri-garland", nameEn: "Flower garland", nameTe: "పూల మాల", quantity: 2 },
  { slug: "samagri-jenu", nameEn: "Jenu", nameTe: "జేను", quantity: 2 },
  { slug: "samagri-head-band", nameEn: "Head band", nameTe: "తలపట్టీ", quantity: 2 },
  { slug: "samagri-ghee", nameEn: "Ghee", nameTe: "నెయ్యి", packEn: "250 ml", packTe: "250 మి.లీ." },
  { slug: "samagri-honey", nameEn: "Honey", nameTe: "తేనె", packEn: "250 ml", packTe: "250 మి.లీ." },
  { slug: "samagri-rose-water", nameEn: "Rose water", nameTe: "పన్నీరు", packEn: "250 ml", packTe: "250 మి.లీ." },
  { slug: "samagri-gomutra", nameEn: "Gomutra", nameTe: "గోమూత్రం", packEn: "100 ml", packTe: "100 మి.లీ." },
  { slug: "samagri-gangajal", nameEn: "Gangajal", nameTe: "గంగాజలం", packEn: "100 ml", packTe: "100 మి.లీ." },
  { slug: "samagri-oil", nameEn: "Oil", nameTe: "నూనె", packEn: "500 ml", packTe: "500 మి.లీ." },
  { slug: "samagri-muggu-colours", nameEn: "Muggu colours", nameTe: "ముగ్గు రంగులు", packEn: "500g", packTe: "500 గ్రా" },
  { slug: "samagri-backdrop", nameEn: "Backdrop", nameTe: "నేపథ్యం" },
  { slug: "samagri-asanam", nameEn: "Asanam", nameTe: "ఆసనం" },
  { slug: "samagri-god-asanam", nameEn: "Deity asanam", nameTe: "దేవత ఆసనం" },
  { slug: "samagri-dona-cups", nameEn: "Dona cups", nameTe: "దోనెలు", quantity: 25 },
  { slug: "samagri-khandwa", nameEn: "Khandwa", nameTe: "ఖండ్వా" },
  { slug: "samagri-blouse-pieces", nameEn: "Blouse pieces", nameTe: "జాకెట్ పీసు" },
  { slug: "samagri-umbrella", nameEn: "Umbrella", nameTe: "గొడుగు" },
  { slug: "samagri-shubh-labh", nameEn: "Shubh Labh sticker", nameTe: "శుభ లాభ్ స్టిక్కర్" },
  { slug: "samagri-peacock-feathers", nameEn: "Peacock feathers", nameTe: "నెమలి ఈకలు", packEn: "small bunch", packTe: "చిన్న కట్ట" },
  { slug: "samagri-pooja-book", nameEn: "Pooja vidhanam book", nameTe: "పూజా విధానం పుస్తకం" },
];

export const ganeshMegaOfficeItems: GaneshSamagriLine[] = [
  { slug: "samagri-eco-ganesh-idol", nameEn: "Eco-friendly clay Ganesh idol", nameTe: "పర్యావరణ అనుకూల మట్టి గణేష్ విగ్రహం" },
  { slug: "samagri-markatam-ganesh", nameEn: "Markatam Ganesh", nameTe: "మార్కటం గణేష్" },
  { slug: "samagri-turmeric", nameEn: "Turmeric (Pasupu)", nameTe: "పసుపు", packEn: "50g", packTe: "50 గ్రా" },
  { slug: "samagri-kumkum", nameEn: "Kumkum", nameTe: "కుంకుమ", packEn: "50g", packTe: "50 గ్రా" },
  { slug: "samagri-sindoor", nameEn: "Sindoor", nameTe: "సింధూరం", packEn: "10g", packTe: "10 గ్రా" },
  { slug: "samagri-bukka", nameEn: "Bukka", nameTe: "బుక్కా", quantity: 12 },
  { slug: "samagri-gulal", nameEn: "Gulal", nameTe: "గులాల్", quantity: 12 },
  { slug: "samagri-rice-flour", nameEn: "Rice flour", nameTe: "బియ్యం పిండి", packEn: "500g", packTe: "500 గ్రా" },
  { slug: "samagri-rice", nameEn: "Rice", nameTe: "బియ్యం", packEn: "2500g", packTe: "2500 గ్రా" },
  { slug: "samagri-astagandham", nameEn: "Astagandham", nameTe: "అష్టగంధం", packEn: "100g", packTe: "100 గ్రా" },
  { slug: "samagri-javadhu", nameEn: "Javadhu", nameTe: "జావాదు", packEn: "50g", packTe: "50 గ్రా" },
  { slug: "samagri-attar", nameEn: "Attar", nameTe: "అత్తరు", packEn: "1 bottle", packTe: "1 సీసా" },
  { slug: "samagri-dhoop-cups", nameEn: "Dhoop cups", nameTe: "ధూపం కప్పులు", quantity: 30 },
  { slug: "samagri-incense", nameEn: "Incense sticks", nameTe: "అగరబత్తులు", packEn: "5 packs", packTe: "5 ప్యాక్‌లు", quantity: 5 },
  { slug: "samagri-camphor", nameEn: "Camphor", nameTe: "కర్పూరం", packEn: "150g", packTe: "150 గ్రా" },
  { slug: "samagri-pacha-karpuram", nameEn: "Pacha karpuram", nameTe: "పచ్చ కర్పూరం", packEn: "50g", packTe: "50 గ్రా" },
  { slug: "samagri-cotton-wicks", nameEn: "Cotton wicks", nameTe: "వత్తులు", packEn: "5 packs", packTe: "5 ప్యాక్‌లు", quantity: 5 },
  { slug: "samagri-puvvu-wicks", nameEn: "Puvvu vathulu", nameTe: "పువ్వు వత్తులు", packEn: "2 packs", packTe: "2 ప్యాక్‌లు", quantity: 2 },
  { slug: "samagri-jileda-wicks", nameEn: "Jileda vathulu", nameTe: "జిలేడు వత్తులు", packEn: "2 packs", packTe: "2 ప్యాక్‌లు", quantity: 2 },
  { slug: "samagri-puja-vastras", nameEn: "Puja vastras", nameTe: "పూజా వస్త్రాలు", quantity: 2 },
  { slug: "samagri-akhanda-deepam", nameEn: "Akhanda deepam", nameTe: "అఖండ దీపం", quantity: 2 },
  { slug: "samagri-dates", nameEn: "Dates", nameTe: "ఖర్జూరాలు", packEn: "250g", packTe: "250 గ్రా" },
  { slug: "samagri-turmeric-roots", nameEn: "Turmeric roots", nameTe: "పసుపు కొమ్ములు", quantity: 21 },
  { slug: "samagri-betel-nuts", nameEn: "Betel nuts (Vakkalu)", nameTe: "వక్కలు", quantity: 25 },
  { slug: "samagri-poha", nameEn: "Poha (Atukulu)", nameTe: "అటుకులు", packEn: "500g", packTe: "500 గ్రా" },
  { slug: "samagri-jaggery", nameEn: "Jaggery", nameTe: "బెల్లం", packEn: "500g", packTe: "500 గ్రా" },
  { slug: "samagri-cloves", nameEn: "Cloves", nameTe: "లవంగాలు", packEn: "50g", packTe: "50 గ్రా" },
  { slug: "samagri-cardamom", nameEn: "Cardamom", nameTe: "యాలకులు", packEn: "50g", packTe: "50 గ్రా" },
  { slug: "samagri-white-thread", nameEn: "White thread", nameTe: "తెల్ల దారం", quantity: 2 },
  { slug: "samagri-sutli", nameEn: "Sutli thread", nameTe: "సుత్లీ దారం", quantity: 2 },
  { slug: "samagri-moli-thread", nameEn: "Moli thread", nameTe: "మౌలి దారం", quantity: 25 },
  { slug: "samagri-garland", nameEn: "Flower garland", nameTe: "పూల మాల", quantity: 5 },
  { slug: "samagri-jenu", nameEn: "Jenu", nameTe: "జేను", quantity: 5 },
  { slug: "samagri-head-band", nameEn: "Head band", nameTe: "తలపట్టీ", quantity: 5 },
  { slug: "samagri-ghee", nameEn: "Ghee", nameTe: "నెయ్యి", packEn: "500 ml", packTe: "500 మి.లీ." },
  { slug: "samagri-honey", nameEn: "Honey", nameTe: "తేనె", packEn: "500 ml", packTe: "500 మి.లీ." },
  { slug: "samagri-rose-water", nameEn: "Rose water", nameTe: "పన్నీరు", packEn: "500 ml", packTe: "500 మి.లీ." },
  { slug: "samagri-gomutra", nameEn: "Gomutra", nameTe: "గోమూత్రం", packEn: "250 ml", packTe: "250 మి.లీ." },
  { slug: "samagri-gangajal", nameEn: "Gangajal", nameTe: "గంగాజలం", packEn: "250 ml", packTe: "250 మి.లీ." },
  { slug: "samagri-oil", nameEn: "Oil", nameTe: "నూనె", packEn: "1000 ml", packTe: "1000 మి.లీ." },
  { slug: "samagri-muggu-colours", nameEn: "Muggu colours", nameTe: "ముగ్గు రంగులు", packEn: "1000g", packTe: "1000 గ్రా" },
  { slug: "samagri-backdrop", nameEn: "Backdrop", nameTe: "నేపథ్యం" },
  { slug: "samagri-asanam", nameEn: "Asanam", nameTe: "ఆసనం" },
  { slug: "samagri-god-asanam", nameEn: "Deity asanam", nameTe: "దేవత ఆసనం" },
  { slug: "samagri-dona-cups", nameEn: "Dona cups", nameTe: "దోనెలు", quantity: 50 },
  { slug: "samagri-khandwa", nameEn: "Khandwa", nameTe: "ఖండ్వా" },
  { slug: "samagri-blouse-pieces", nameEn: "Blouse pieces", nameTe: "జాకెట్ పీసు", quantity: 2 },
  { slug: "samagri-umbrella", nameEn: "Umbrella", nameTe: "గొడుగు" },
  { slug: "samagri-shubh-labh", nameEn: "Shubh Labh sticker", nameTe: "శుభ లాభ్ స్టిక్కర్", quantity: 2 },
  { slug: "samagri-peacock-feathers", nameEn: "Peacock feathers", nameTe: "నెమలి ఈకలు", packEn: "1 bunch", packTe: "1 కట్ట" },
  { slug: "samagri-pooja-book", nameEn: "Pooja vidhanam book", nameTe: "పూజా విధానం పుస్తకం" },
];

export const ganeshMegaMandapamItems: GaneshSamagriLine[] = [
  { slug: "samagri-eco-ganesh-idol", nameEn: "Eco-friendly clay Ganesh idol", nameTe: "పర్యావరణ అనుకూల మట్టి గణేష్ విగ్రహం" },
  { slug: "samagri-markatam-ganesh", nameEn: "Markatam Ganesh", nameTe: "మార్కటం గణేష్" },
  { slug: "samagri-turmeric", nameEn: "Turmeric (Pasupu)", nameTe: "పసుపు", packEn: "250g", packTe: "250 గ్రా" },
  { slug: "samagri-kumkum", nameEn: "Kumkum", nameTe: "కుంకుమ", packEn: "250g", packTe: "250 గ్రా" },
  { slug: "samagri-sindoor", nameEn: "Sindoor", nameTe: "సింధూరం", packEn: "100g", packTe: "100 గ్రా" },
  { slug: "samagri-bukka", nameEn: "Bukka", nameTe: "బుక్కా", quantity: 50 },
  { slug: "samagri-gulal", nameEn: "Gulal", nameTe: "గులాల్", quantity: 50 },
  { slug: "samagri-rice-flour", nameEn: "Rice flour", nameTe: "బియ్యం పిండి", packEn: "1000g", packTe: "1000 గ్రా" },
  { slug: "samagri-rice", nameEn: "Rice", nameTe: "బియ్యం", packEn: "5000g", packTe: "5000 గ్రా" },
  { slug: "samagri-astagandham", nameEn: "Astagandham", nameTe: "అష్టగంధం", packEn: "250g", packTe: "250 గ్రా" },
  { slug: "samagri-javadhu", nameEn: "Javadhu", nameTe: "జావాదు", packEn: "100g", packTe: "100 గ్రా" },
  { slug: "samagri-attar", nameEn: "Attar", nameTe: "అత్తరు", quantity: 2 },
  { slug: "samagri-dhoop-cups", nameEn: "Dhoop cups", nameTe: "ధూపం కప్పులు", quantity: 100 },
  { slug: "samagri-incense", nameEn: "Incense sticks", nameTe: "అగరబత్తులు", packEn: "10 packs", packTe: "10 ప్యాక్‌లు", quantity: 10 },
  { slug: "samagri-camphor", nameEn: "Camphor", nameTe: "కర్పూరం", packEn: "500g", packTe: "500 గ్రా" },
  { slug: "samagri-pacha-karpuram", nameEn: "Pacha karpuram", nameTe: "పచ్చ కర్పూరం", packEn: "100g", packTe: "100 గ్రా" },
  { slug: "samagri-cotton-wicks", nameEn: "Cotton wicks", nameTe: "వత్తులు", packEn: "10 packs", packTe: "10 ప్యాక్‌లు", quantity: 10 },
  { slug: "samagri-puvvu-wicks", nameEn: "Puvvu vathulu", nameTe: "పువ్వు వత్తులు", packEn: "5 packs", packTe: "5 ప్యాక్‌లు", quantity: 5 },
  { slug: "samagri-jileda-wicks", nameEn: "Jileda vathulu", nameTe: "జిలేడు వత్తులు", packEn: "5 packs", packTe: "5 ప్యాక్‌లు", quantity: 5 },
  { slug: "samagri-puja-vastras", nameEn: "Puja vastras", nameTe: "పూజా వస్త్రాలు", quantity: 3 },
  { slug: "samagri-akhanda-deepam", nameEn: "Akhanda deepam", nameTe: "అఖండ దీపం", quantity: 4 },
  { slug: "samagri-dates", nameEn: "Dates", nameTe: "ఖర్జూరాలు", packEn: "500g", packTe: "500 గ్రా" },
  { slug: "samagri-turmeric-roots", nameEn: "Turmeric roots", nameTe: "పసుపు కొమ్ములు", quantity: 50 },
  { slug: "samagri-betel-nuts", nameEn: "Betel nuts (Vakkalu)", nameTe: "వక్కలు", quantity: 100 },
  { slug: "samagri-poha", nameEn: "Poha (Atukulu)", nameTe: "అటుకులు", packEn: "1000g", packTe: "1000 గ్రా" },
  { slug: "samagri-jaggery", nameEn: "Jaggery", nameTe: "బెల్లం", packEn: "2000g", packTe: "2000 గ్రా" },
  { slug: "samagri-cloves", nameEn: "Cloves", nameTe: "లవంగాలు", packEn: "100g", packTe: "100 గ్రా" },
  { slug: "samagri-cardamom", nameEn: "Cardamom", nameTe: "యాలకులు", packEn: "100g", packTe: "100 గ్రా" },
  { slug: "samagri-white-thread", nameEn: "White thread", nameTe: "తెల్ల దారం", quantity: 5 },
  { slug: "samagri-sutli", nameEn: "Sutli thread", nameTe: "సుత్లీ దారం", quantity: 5 },
  { slug: "samagri-moli-thread", nameEn: "Moli thread", nameTe: "మౌలి దారం", quantity: 100 },
  { slug: "samagri-garland", nameEn: "Flower garland", nameTe: "పూల మాల", quantity: 20 },
  { slug: "samagri-jenu", nameEn: "Jenu", nameTe: "జేను", quantity: 20 },
  { slug: "samagri-head-band", nameEn: "Head band", nameTe: "తలపట్టీ", quantity: 20 },
  { slug: "samagri-ghee", nameEn: "Ghee", nameTe: "నెయ్యి", packEn: "1000 ml", packTe: "1000 మి.లీ." },
  { slug: "samagri-honey", nameEn: "Honey", nameTe: "తేనె", packEn: "1000 ml", packTe: "1000 మి.లీ." },
  { slug: "samagri-rose-water", nameEn: "Rose water", nameTe: "పన్నీరు", packEn: "1000 ml", packTe: "1000 మి.లీ." },
  { slug: "samagri-gomutra", nameEn: "Gomutra", nameTe: "గోమూత్రం", packEn: "500 ml", packTe: "500 మి.లీ." },
  { slug: "samagri-gangajal", nameEn: "Gangajal", nameTe: "గంగాజలం", packEn: "500 ml", packTe: "500 మి.లీ." },
  { slug: "samagri-oil", nameEn: "Oil", nameTe: "నూనె", packEn: "3000 ml", packTe: "3000 మి.లీ." },
  { slug: "samagri-muggu-colours", nameEn: "Muggu colours", nameTe: "ముగ్గు రంగులు", packEn: "3000g", packTe: "3000 గ్రా" },
  { slug: "samagri-backdrop", nameEn: "Backdrop", nameTe: "నేపథ్యం" },
  { slug: "samagri-asanam", nameEn: "Asanam", nameTe: "ఆసనం", quantity: 2 },
  { slug: "samagri-god-asanam", nameEn: "Deity asanam", nameTe: "దేవత ఆసనం" },
  { slug: "samagri-dona-cups", nameEn: "Dona cups", nameTe: "దోనెలు", quantity: 200 },
  { slug: "samagri-khandwa", nameEn: "Khandwa", nameTe: "ఖండ్వా", quantity: 2 },
  { slug: "samagri-blouse-pieces", nameEn: "Blouse pieces", nameTe: "జాకెట్ పీసు", quantity: 3 },
  { slug: "samagri-umbrella", nameEn: "Umbrella", nameTe: "గొడుగు" },
  { slug: "samagri-shubh-labh", nameEn: "Shubh Labh sticker", nameTe: "శుభ లాభ్ స్టిక్కర్", quantity: 5 },
  { slug: "samagri-peacock-feathers", nameEn: "Peacock feathers", nameTe: "నెమలి ఈకలు", quantity: 2 },
  { slug: "samagri-pooja-book", nameEn: "Pooja vidhanam book", nameTe: "పూజా విధానం పుస్తకం", quantity: 2 },
];

export const ganeshHomamItems: GaneshSamagriLine[] = [
  { slug: "samagri-homa-powder", nameEn: "Homa powder", nameTe: "హోమం పొడి", packEn: "1 kg", packTe: "1కిలో" },
  { slug: "samagri-poha", nameEn: "Poha (Atukulu)", nameTe: "అటుకులు", packEn: "1/2 kg", packTe: "1/2కిలో" },
  { slug: "samagri-jaggery", nameEn: "Jaggery", nameTe: "బెల్లం" },
  { slug: "samagri-navadhanyalu", nameEn: "Navadhanyalu", nameTe: "నవధాన్యాలు" },
  { slug: "samagri-rice-flour", nameEn: "Rice flour", nameTe: "బియ్యం పిండి" },
  { slug: "samagri-purnahuti", nameEn: "Purnahuti", nameTe: "పూర్ణాహుతి" },
  { slug: "samagri-betel-leaves", nameEn: "Betel leaves", nameTe: "తామలపాకులు" },
  { slug: "samagri-fruits", nameEn: "Fruits", nameTe: "పండ్లు" },
  { slug: "samagri-flowers", nameEn: "Flowers", nameTe: "పువ్వులు" },
  { slug: "samagri-dry-fruits", nameEn: "Dry fruits", nameTe: "డ్రై ఫ్రూట్స్" },
  { slug: "samagri-samithalu", nameEn: "Samithalu (homa sticks)", nameTe: "సమితలు" },
  { slug: "samagri-ghee", nameEn: "Ghee", nameTe: "నెయ్యి" },
  { slug: "samagri-camphor", nameEn: "Arati camphor", nameTe: "హారతి కర్పూరం" },
  { slug: "samagri-isthari-leaves", nameEn: "Isthari leaves (Durva)", nameTe: "ఇస్తరి ఆకులు" },
  { slug: "samagri-homa-stand", nameEn: "Homa stand", nameTe: "హోమం స్టాండ్" },
  { slug: "samagri-dhoti", nameEn: "Dhoti", nameTe: "ధోతి" },
  { slug: "samagri-blouse-pieces", nameEn: "Blouse piece (Jacket piece)", nameTe: "జాకెట్ పీసు" },
  { slug: "samagri-coconuts", nameEn: "Coconuts", nameTe: "కొబ్బరికాయలు", quantity: 2 },
];

export const ganeshOptionalOfferings: GaneshSamagriLine[] = [
  { slug: "samagri-21-patri", nameEn: "21 patri pack", nameTe: "21 రకాల పత్రి", optional: true },
  { slug: "samagri-isthari-leaves", nameEn: "Durva / isthari leaves", nameTe: "దూర్వా గడ్డి", optional: true },
  { slug: "samagri-undrallu", nameEn: "Undrallu", nameTe: "ఉండ్రాళ్లు / మోదకం", optional: true },
  { slug: "samagri-laddu", nameEn: "Laddu", nameTe: "లడ్డూ", optional: true },
  { slug: "samagri-panchamritam", nameEn: "Panchamritam pack", nameTe: "పంచామృతం ప్యాక్", optional: true },
  { slug: "samagri-flowers", nameEn: "Loose flowers", nameTe: "విడిపూలు / పువ్వులు", optional: true },
];

function withOptionalOfferings(items: GaneshSamagriLine[]): GaneshSamagriLine[] {
  const slugs = new Set(items.map((item) => item.slug));
  return [...items, ...ganeshOptionalOfferings.filter((extra) => !slugs.has(extra.slug))];
}

export const ganeshKitItemsBySlug: Record<string, GaneshSamagriLine[]> = {
  "ganesh-mini-home-puja": withOptionalOfferings(ganeshMiniHomeItems),
  "ganesh-mini-office-puja": withOptionalOfferings(ganeshMiniOfficeItems),
  "ganesh-mini-mandapam": withOptionalOfferings(ganeshMiniMandapamItems),
  "ganesh-mega-home-puja": withOptionalOfferings(ganeshMegaHomeItems),
  "ganesh-mega-office-puja": withOptionalOfferings(ganeshMegaOfficeItems),
  "ganesh-mega-mandapam": withOptionalOfferings(ganeshMegaMandapamItems),
  "ganesh-puja-homam-samagri": withOptionalOfferings(ganeshHomamItems),
};

export function ganeshLineLabel(line: GaneshSamagriLine, locale: "en" | "te") {
  const name = locale === "te" ? line.nameTe : line.nameEn;
  const pack = locale === "te" ? line.packTe : line.packEn;
  const qty = !pack && line.quantity && line.quantity > 1 ? ` ×${line.quantity}` : "";
  return pack ? `${name} — ${pack}` : `${name}${qty}`;
}

export function ganeshSelectedKeys(items: GaneshSamagriLine[], chosenOptional: Set<string>) {
  return items.filter((item) => !item.optional || chosenOptional.has(item.slug)).map((item) => item.slug);
}

