import type { GuideKnowledgeEntry } from './knowledge-types';

/**
 * Data-driven guide knowledge for Pavitra Seva.
 * Add festivals/poojas here (or via catalog sync later) without changing chatbot UI.
 * Kit slugs must match live catalog products — never invent prices in chat.
 */
export const GUIDE_KNOWLEDGE: GuideKnowledgeEntry[] = [
  {
    id: 'festival-ganesh',
    kind: 'festival',
    aliases: [
      'ganesh',
      'ganesha',
      'ganapati',
      'vinayaka',
      'vinayaka chavithi',
      'ganesh chaturthi',
      'గణేష్',
      'వినాయక',
      'चतुर्थी',
      'गणेश',
    ],
    name: {
      en: 'Ganesh Chaturthi',
      te: 'వినాయక చవితి',
      hi: 'गणेश चतुर्थी',
    },
    description: {
      en: 'Ganesh Chaturthi celebrates Lord Ganesha, traditionally worshipped as the remover of obstacles and associated with wisdom and new beginnings. Families bring clay idols, perform Pooja, offer Naivedyam, and conclude with Visarjan according to their customs.',
      te: 'వినాయక చవితి గణేశుని జననోత్సవం. కుటుంబాలు మట్టి విగ్రహం తీసుకువచ్చి పూజ చేసి, నైవేద్యం సమర్పించి, ఆచారం ప్రకారం విసర్జన చేస్తారు.',
      hi: 'गणेश चतुर्थी भगवान गणेश का उत्सव है। परिवार मिट्टी की मूर्ति लाते हैं, पूजा करते हैं, नैवेद्य अर्पित करते हैं और परंपरा अनुसार विसर्जन करते हैं।',
    },
    significance: {
      en: 'Ganesha is invoked at the start of new ventures. Practices can vary by region and family tradition.',
      te: 'కొత్త పనుల మొదట గణేశుని ప్రార్థిస్తారు. ఆచారాలు ప్రాంతం, కుటుంబం బట్టి మారవచ్చు.',
    },
    practices: [
      'Install an eco-friendly clay idol facing east or north',
      'Perform Prana Pratishtha',
      'Offer durva, flowers, and modak / undrallu',
      'Aarti morning and evening',
      'Visarjan on the chosen day',
    ],
    samagri: [
      'Eco-friendly clay Ganesh idol',
      'Turmeric',
      'Kumkum',
      'Gandham',
      'Akshatalu',
      'Camphor',
      'Incense',
      'Oil / ghee',
      'Coconut',
      'Betel leaves',
      'Durva grass',
      'Modak / undrallu',
      'Pooja vidhanam',
    ],
    vidhiSteps: [
      'Clean the pooja space and place the idol on a chowki',
      'Invoke with Prana Pratishtha',
      'Offer padya, arghya, flowers, durva, and naivedyam',
      'Perform aarti with camphor and incense',
      'Thank Ganesha and immerse the clay murti safely (visarjan)',
    ],
    kitSlugs: [
      'ganesh-mini-home-puja',
      'ganesh-mini-office-puja',
      'ganesh-mini-mandapam',
      'ganesh-mega-home-puja',
      'ganesh-mega-office-puja',
      'ganesh-mega-mandapam',
      'ganapati-special-samagri',
      'ganesh-puja-homam-samagri',
    ],
    pagePaths: ['/festivals/ganesh', '/kits/ganesh-mini-home-puja', '/poojas/ganapati'],
    relatedIds: ['pooja-ganapati', 'service-poojari'],
    faqs: [
      {
        q: 'How long should the idol stay?',
        a: 'Families keep the idol from 1.5 to 11 days depending on custom. Choose a visarjan day that suits your household.',
      },
    ],
  },
  {
    id: 'festival-varalakshmi',
    kind: 'festival',
    aliases: ['varalakshmi', 'varalakshmi vratam', 'varalakshmi vratham', 'వరలక్ష్మి', 'वरलक्ष्मी'],
    name: {
      en: 'Varalakshmi Vratam',
      te: 'వరలక్ష్మీ వ్రతం',
      hi: 'वरलक्ष्मी व्रतम्',
    },
    description: {
      en: 'Varalakshmi Vratam is observed by many women seeking the blessings of Goddess Lakshmi for prosperity and family wellbeing. A kalash representing the goddess is worshipped with traditional offerings.',
      te: 'వరలక్ష్మీ వ్రతం లక్ష్మీదేవి అనుగ్రహం కోసం చేసే వ్రతం. కలశ రూపంలో అమ్మవారిని పూజిస్తారు.',
    },
    samagri: ['Kalash', 'Turmeric', 'Kumkum', 'Flowers', 'Blouse piece', 'Bangles', 'Sweets', 'Fruits'],
    kitSlugs: ['varalakshmi-vratam-samagri'],
    pagePaths: ['/festivals/varalakshmi', '/kits/varalakshmi-vratam-samagri', '/poojas/varalakshmi'],
  },
  {
    id: 'festival-navratri',
    kind: 'festival',
    aliases: ['navratri', 'sharad navratri', 'durga', 'నవరాత్రి', 'नवरात्रि'],
    name: { en: 'Sharad Navratri', te: 'శరద్ నవరాత్రి', hi: 'शरद नवरात्रि' },
    description: {
      en: 'Navratri honors nine forms of Goddess Durga over nine nights, culminating in Vijayadashami. Many install a kalash, keep a lamp, and observe fasting or garba.',
      te: 'నవరాత్రి తొమ్మిది రూపాల దుర్గా దేవిని తొమ్మిది రాత్రులు పూజించే ఉత్సవం.',
    },
    practices: ['Install kalash on day one', 'Daily aarti', 'Kanya pooja near the end'],
    samagri: ['Kalash', 'Coconut', 'Mango leaves', 'Barley seeds', 'Red cloth', 'Oil lamp'],
    kitSlugs: ['navratri-special-samagri'],
    pagePaths: ['/festivals/navratri', '/kits/navratri-special-samagri', '/poojas/navratri'],
  },
  {
    id: 'festival-diwali',
    kind: 'festival',
    aliases: ['diwali', 'deepavali', 'lakshmi pooja', 'దీపావళి', 'दिवाली'],
    name: { en: 'Diwali', te: 'దీపావళి', hi: 'दिवाली' },
    description: {
      en: 'Diwali, the festival of lights, includes Lakshmi Pooja for prosperity. Homes are cleaned, lit with diyas, and sweets are shared.',
      te: 'దీపావళి వెలుగుల పండుగ. లక్ష్మీ పూజ, దీపాలు, మిఠాయిలు ముఖ్యం.',
    },
    samagri: ['Diyas', 'Rangoli', 'Lakshmi-Ganesha idols', 'Sweets', 'Coins', 'Flowers'],
    kitSlugs: ['lakshmi-special-samagri'],
    pagePaths: ['/festivals/diwali', '/kits/lakshmi-special-samagri', '/poojas/diwali'],
  },
  {
    id: 'festival-janmashtami',
    kind: 'festival',
    aliases: ['janmashtami', 'krishna', 'జన్మాష్టమి', 'जन्माष्टमी'],
    name: { en: 'Janmashtami', te: 'జన్మాష్టమి', hi: 'जन्माष्टमी' },
    description: {
      en: 'Janmashtami celebrates the birth of Lord Krishna with fasting, bhajans, and midnight aarti in many homes and temples.',
      te: 'జన్మాష్టమి శ్రీకృష్ణుని జననోత్సవం.',
    },
    kitSlugs: ['janmashtami-special-samagri'],
    pagePaths: ['/festivals/janmashtami', '/kits/janmashtami-special-samagri'],
  },
  {
    id: 'festival-dussehra',
    kind: 'festival',
    aliases: ['dussehra', 'vijayadashami', 'దసరా', 'విజయదశమి', 'दशहरा'],
    name: { en: 'Dussehra / Vijayadashami', te: 'దసరా / విజయదశమి', hi: 'दशहरा' },
    description: {
      en: 'Vijayadashami marks the victory of dharma. Many perform Ayudha Pooja and begin new learning (Vidyarambham) around this time.',
      te: 'విజయదశమి ధర్మ విజయం. ఆయుధ పూజ, విద్యారంభం చాలా చోట్ల చేస్తారు.',
    },
    kitSlugs: ['saraswati-special-samagri'],
    pagePaths: ['/festivals/dussehra'],
  },
  {
    id: 'festival-ugadi',
    kind: 'festival',
    aliases: ['ugadi', 'ugādi', 'యుగాది', 'उगादि'],
    name: { en: 'Ugadi', te: 'యుగాది', hi: 'उगादि' },
    description: {
      en: 'Ugadi marks the traditional new year in many Telugu and Kannada households, with Ugadi pachadi and fresh beginnings.',
      te: 'యుగాది తెలుగు కొత్త సంవత్సరాది. ఉగాది పచ్చడి ప్రత్యేకం.',
    },
    kitSlugs: ['ugadi-special-samagri'],
    pagePaths: ['/festivals/ugadi', '/kits/ugadi-special-samagri'],
  },
  {
    id: 'festival-sankranti',
    kind: 'festival',
    aliases: ['sankranti', 'makara sankranti', 'pongal', 'సంక్రాంతి', 'संक्रांति'],
    name: { en: 'Makara Sankranti', te: 'మకర సంక్రాంతి', hi: 'मकर संक्रांति' },
    description: {
      en: 'Sankranti celebrates the sun’s northward journey with harvest gratitude, sweets like pongal/ariselu, and family gatherings.',
      te: 'సంక్రాంతి పంటల పండుగ. అరిసెలు, పిండి వంటకాలు, కుటుంబ సమావేశాలు.',
    },
    kitSlugs: ['general-pooja-samagri-kit'],
    pagePaths: ['/festivals/sankranti'],
  },
  {
    id: 'festival-shivaratri',
    kind: 'festival',
    aliases: ['shivaratri', 'maha shivaratri', 'శివరాత్రి', 'शिवरात्रि'],
    name: { en: 'Maha Shivaratri', te: 'మహా శివరాత్రి', hi: 'महा शिवरात्रि' },
    description: {
      en: 'Maha Shivaratri is an all-night vigil for Lord Shiva with abhishekam, bilva leaves, and fasting in many traditions.',
      te: 'మహా శివరాత్రి శివుని జాగరణ. అభిషేకం, బిల్వ పత్రాలు ముఖ్యం.',
    },
    kitSlugs: ['shiva-special-samagri'],
    pagePaths: ['/festivals/shivaratri', '/kits/shiva-special-samagri', '/poojas/shiva'],
  },
  {
    id: 'festival-rama-navami',
    kind: 'festival',
    aliases: ['rama navami', 'ram navami', 'రామ నవమి', 'राम नवमी'],
    name: { en: 'Rama Navami', te: 'శ్రీ రామ నవమి', hi: 'राम नवमी' },
    description: {
      en: 'Rama Navami celebrates the birth of Lord Rama with kalyanam, chanting, and prasad distribution in many communities.',
      te: 'శ్రీ రామ నవమి రాముని జననోత్సవం.',
    },
    kitSlugs: ['rama-navami-special-samagri'],
    pagePaths: ['/festivals/rama-navami'],
  },
  {
    id: 'pooja-ganapati',
    kind: 'pooja',
    aliases: ['ganapati pooja', 'ganesh pooja', 'vinayaka pooja', 'గణపతి పూజ'],
    name: { en: 'Ganapati Pooja', te: 'గణపతి పూజ', hi: 'गणपति पूजा' },
    description: {
      en: 'A home or office Ganapati Pooja typically includes Prana Pratishtha, offerings of durva and modak, and aarti. Practices can vary by region and family tradition.',
      te: 'ఇంటి గణపతి పూజలో ప్రాణ ప్రతిష్ఠ, దూర్వా, మోదకం, హారతి ఉంటాయి. ఆచారాలు మారవచ్చు.',
    },
    samagri: [
      'Clay Ganesh idol',
      'Durva',
      'Red flowers',
      'Modak / undrallu',
      'Turmeric',
      'Kumkum',
      'Camphor',
    ],
    kitSlugs: ['ganesh-mini-home-puja', 'ganapati-special-samagri'],
    pagePaths: ['/poojas/ganapati', '/kits/ganesh-mini-home-puja'],
  },
  {
    id: 'pooja-lakshmi',
    kind: 'pooja',
    aliases: ['lakshmi pooja', 'lakshmi puja', 'లక్ష్మీ పూజ', 'लक्ष्मी पूजा'],
    name: { en: 'Lakshmi Pooja', te: 'లక్ష్మీ పూజ', hi: 'लक्ष्मी पूजा' },
    description: {
      en: 'Lakshmi Pooja seeks blessings for prosperity. Commonly performed on Diwali evening and on Fridays in many homes.',
      te: 'లక్ష్మీ పూజ సంపద, శుభం కోసం. దీపావళి సాయంత్రం, శుక్రవారాల్లో చాలా ఇళ్లలో చేస్తారు.',
    },
    kitSlugs: ['lakshmi-special-samagri'],
    pagePaths: ['/poojas/lakshmi', '/kits/lakshmi-special-samagri'],
  },
  {
    id: 'pooja-shiva',
    kind: 'pooja',
    aliases: ['shiva pooja', 'rudrabhishekam', 'శివ పూజ', 'शिव पूजा'],
    name: { en: 'Shiva Pooja', te: 'శివ పూజ', hi: 'शिव पूजा' },
    description: {
      en: 'Shiva Pooja often includes abhishekam with water/milk and offering bilva leaves. Temple and family customs differ.',
      te: 'శివ పూజలో అభిషేకం, బిల్వ పత్రాలు ముఖ్యం.',
    },
    kitSlugs: ['shiva-special-samagri'],
    pagePaths: ['/poojas/shiva', '/kits/shiva-special-samagri'],
  },
  {
    id: 'pooja-satyanarayana',
    kind: 'pooja',
    aliases: ['satyanarayana', 'satyanarayan', 'సత్యనారాయణ', 'सत्यनारायण'],
    name: {
      en: 'Satyanarayana Pooja',
      te: 'సత్యనారాయణ స్వామి వ్రతం',
      hi: 'सत्यनारायण पूजा',
    },
    description: {
      en: 'Satyanarayana Vratam is commonly performed for gratitude and auspicious beginnings, with katha and prasad. Invite a Poojari when you prefer guided performance.',
      te: 'సత్యనారాయణ వ్రతం కృతజ్ఞత, శుభారంభాలకు చేస్తారు. కావాలంటే పూజారిని బుక్ చేయవచ్చు.',
    },
    kitSlugs: ['general-pooja-samagri-kit', 'vishnu-special-samagri'],
    pagePaths: ['/poojas', '/priests', '/kits'],
  },
  {
    id: 'pooja-gruhapravesham',
    kind: 'pooja',
    aliases: ['gruhapravesham', 'griha pravesh', 'house warming', 'గృహప్రవేశం', 'गृह प्रवेश'],
    name: { en: 'Gruhapravesham', te: 'గృహప్రవేశం', hi: 'गृह प्रवेश' },
    description: {
      en: 'Gruhapravesham welcomes a family into a new home with purification rites. Muhurtham and exact procedure should follow your family priest or local tradition.',
      te: 'గృహప్రవేశం కొత్త ఇంటికి శుభారంభం. ముహూర్తం, విధి కుటుంబ/పూజారి ఆచారం బట్టి ఉంటాయి.',
    },
    kitSlugs: ['general-pooja-samagri-kit'],
    pagePaths: ['/poojas', '/priests', '/kits'],
  },
  {
    id: 'pooja-saraswati',
    kind: 'pooja',
    aliases: ['saraswati', 'saraswati pooja', 'సరస్వతి', 'सरस्वती'],
    name: { en: 'Saraswati Pooja', te: 'సరస్వతీ పూజ', hi: 'सरस्वती पूजा' },
    description: {
      en: 'Saraswati Pooja honors learning and the arts, often during Navratri / Vijayadashami (Vidyarambham).',
      te: 'సరస్వతీ పూజ విద్య, కళలకు. నవరాత్రి / విజయదశమి సమయంలో చాలా మంది చేస్తారు.',
    },
    kitSlugs: ['saraswati-special-samagri'],
    pagePaths: ['/poojas/saraswati', '/kits/saraswati-special-samagri'],
  },
  {
    id: 'pooja-navagraha',
    kind: 'pooja',
    aliases: ['navagraha', 'నవగ్రహ', 'नवग्रह'],
    name: { en: 'Navagraha Pooja', te: 'నవగ్రహ పూజ', hi: 'नवग्रह पूजा' },
    description: {
      en: 'Navagraha Pooja is performed in many traditions for planetary peace. Treat astrological guidance as traditional belief, not scientific fact.',
      te: 'నవగ్రహ పూజ సాంప్రదాయిక శాంతి కోసం. జ్యోతిష్యాన్ని నమ్మకంగా కాక సాంప్రదాయిక దృష్టితో చూడండి.',
    },
    kitSlugs: ['navagraha-special-samagri'],
    pagePaths: ['/poojas/navagraha', '/kits/navagraha-special-samagri'],
  },
  {
    id: 'pooja-hanuman',
    kind: 'pooja',
    aliases: ['hanuman', 'hanuman jayanti', 'హనుమాన్', 'हनुमान'],
    name: { en: 'Hanuman Pooja / Jayanti', te: 'హనుమాన్ పూజ / జయంతి', hi: 'हनुमान पूजा' },
    description: {
      en: 'Hanuman worship is associated with strength, devotion, and protection. Many recite Hanuman Chalisa on Tuesdays and Saturdays.',
      te: 'హనుమంతుని ఆరాధన భక్తి, ధైర్యం కోసం. మంగళ/శనివారాల్లో చాలా మంది చేస్తారు.',
    },
    kitSlugs: ['hanuman-jayanti-special-samagri'],
    pagePaths: ['/poojas/hanuman'],
  },
  {
    id: 'pooja-vishnu',
    kind: 'pooja',
    aliases: ['vishnu', 'విష్ణు', 'विष्णु'],
    name: { en: 'Vishnu Pooja', te: 'విష్ణు పూజ', hi: 'विष्णु पूजा' },
    description: {
      en: 'Vishnu Pooja includes tulasi, flowers, and naivedyam as commonly followed in Vaishnava homes. Details vary by sampradaya.',
      te: 'విష్ణు పూజలో తులసి, పూలు, నైవేద్యం సాధారణం. సంప్రదాయం బట్టి మారుతుంది.',
    },
    kitSlugs: ['vishnu-special-samagri'],
    pagePaths: ['/poojas/vishnu', '/kits/vishnu-special-samagri'],
  },
  {
    id: 'pooja-surya',
    kind: 'pooja',
    aliases: ['surya', 'surya namaskar', 'సూర్య', 'सूर्य'],
    name: { en: 'Surya Pooja', te: 'సూర్య పూజ', hi: 'सूर्य पूजा' },
    description: {
      en: 'Surya worship is often offered at sunrise with water (arghya). Sunday is traditionally associated with Surya in many households.',
      te: 'సూర్యారాధన సాధారణంగా ఉదయం అర్ఘ్యంతో. ఆదివారం సూర్యునికి ప్రత్యేకం.',
    },
    kitSlugs: ['surya-special-samagri'],
    pagePaths: ['/poojas/surya'],
  },
  {
    id: 'service-poojari',
    kind: 'service',
    aliases: ['poojari', 'priest', 'pandit', 'పూజారి', 'पुरोहित'],
    name: { en: 'Book a Poojari', te: 'పూజారిని బుక్ చేయండి', hi: 'पुजारी बुक करें' },
    description: {
      en: 'Pavitra Seva helps families book Poojaris for home ceremonies when the service is available in your area. Availability is confirmed in the booking flow — we do not invent slots.',
      te: 'పవిత్ర సేవ ద్వారా ఇంటి పూజలకు పూజారిని బుక్ చేయవచ్చు. లభ్యత బుకింగ్‌లోనే నిర్ధారిస్తాం.',
    },
    kitSlugs: [],
    pagePaths: ['/priests'],
  },
  {
    id: 'page-panchang',
    kind: 'page',
    aliases: ['panchang', 'panchangam', 'tithi', 'పంచాంగం', 'पंचांग'],
    name: { en: "Today's Panchangam", te: 'నేటి పంచాంగం', hi: 'आज का पंचांग' },
    description: {
      en: 'Pavitra Seva shows daily panchangam details to help you plan observances. Treat muhurtham advice as traditional guidance and confirm important timings with your family priest when needed.',
      te: 'పవిత్ర సేవలో నిత్య పంచాంగం చూడవచ్చు. ముఖ్య ముహూర్తాలు కుటుంబ పూజారితో నిర్ధారించుకోండి.',
    },
    kitSlugs: [],
    pagePaths: ['/panchang', '/guidance'],
  },
  {
    id: 'page-kits',
    kind: 'page',
    aliases: ['kit', 'samagri kit', 'pooja kit', 'కిట్', 'सामग्री'],
    name: { en: 'Pooja Kits', te: 'పూజా కిట్లు', hi: 'पूजा किट' },
    description: {
      en: 'Pavitra Seva Pooja kits bundle commonly needed Samagri for festivals and deity Poojas. Choose home, office, or mandapam sizes where offered.',
      te: 'పవిత్ర సేవ పూజా కిట్లు పండుగలు, దేవతా పూజలకు సామగ్రిని సమీకరిస్తాయి.',
    },
    kitSlugs: ['general-pooja-samagri-kit'],
    pagePaths: ['/kits', '/samagri'],
  },
];

export function allGuideKitSlugs(): string[] {
  return [...new Set(GUIDE_KNOWLEDGE.flatMap((entry) => entry.kitSlugs))];
}
